-- Create table for Leader Reports
CREATE TABLE IF NOT EXISTS leader_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Leader info
    leader_id TEXT NOT NULL,
    leader_name TEXT,
    
    -- Location & Time
    store_code TEXT NOT NULL,
    area_code TEXT NOT NULL,
    shift_start TIME,
    shift_end TIME,
    
    -- Shift Status Flags
    has_peak BOOLEAN DEFAULT FALSE,
    has_out_of_stock BOOLEAN DEFAULT FALSE,
    has_customer_issue BOOLEAN DEFAULT FALSE,
    
    -- Checklist (stored as JSONB)
    checklist JSONB DEFAULT '{}'::JSONB,
    
    -- Incident Tracking
    observed_issue_code TEXT,
    observed_note TEXT,
    
    -- Staff Feedback
    mood INTEGER,
    khen_emp_id TEXT,
    khen_topic TEXT,
    nhac_emp_id TEXT,
    nhac_topic TEXT,
    
    -- Handover
    next_shift_risk TEXT DEFAULT 'NONE',
    next_shift_note TEXT,
    
    -- Confirmation
    is_confirmed BOOLEAN DEFAULT FALSE
);

-- RLS Policies (Optional, but recommended)
ALTER TABLE leader_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read/write for authenticated users" ON leader_reports
    FOR ALL
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');
