-- Migration V3.11: Module 10 - Financial & Outcome
-- Focus: Daily Revenue Tracking for Decision Engine Correlation

CREATE TABLE IF NOT EXISTS daily_revenue_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code TEXT NOT NULL,
    date DATE NOT NULL,
    gross_sales DECIMAL(15, 2) DEFAULT 0,
    net_sales DECIMAL(15, 2) DEFAULT 0,
    discount_amount DECIMAL(15, 2) DEFAULT 0,
    guest_count INTEGER DEFAULT 0,
    is_finalized BOOLEAN DEFAULT FALSE,
    verified_by_ops BOOLEAN DEFAULT FALSE,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(store_code, date)
);

-- Indexing for lookup
CREATE INDEX IF NOT EXISTS idx_rev_store_date ON daily_revenue_logs(store_code, date);
CREATE INDEX IF NOT EXISTS idx_rev_date ON daily_revenue_logs(date);
