-- Migration V3.13: Operation Metrics (Aggregation Layer)
-- Focus: Aggregating Shift Signals into Daily Store and Staff Performance scores

-- 1. Daily Store Metrics (Top-level Management View)
CREATE TABLE IF NOT EXISTS agg_daily_store_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code TEXT NOT NULL,
    date DATE NOT NULL,
    overall_ops_score DECIMAL(5, 2) DEFAULT 100,
    attendance_score DECIMAL(5, 2) DEFAULT 100,
    execution_score DECIMAL(5, 2) DEFAULT 100,
    incident_score DECIMAL(5, 2) DEFAULT 100,
    compliance_score DECIMAL(5, 2) DEFAULT 100,
    signal_summary JSONB DEFAULT '{}', -- { 'R01': 2, 'R12': 1 }
    incident_count INTEGER DEFAULT 0,
    critical_incident_count INTEGER DEFAULT 0,
    revenue_correlation DECIMAL(5, 2), -- Score based on traffic vs revenue
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(store_code, date)
);

-- 2. Daily Staff Metrics (Individual Performance Tracker)
CREATE TABLE IF NOT EXISTS agg_daily_staff_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id BIGINT NOT NULL,
    date DATE NOT NULL,
    store_code TEXT,
    trust_score_delta DECIMAL(5, 2) DEFAULT 0,
    ops_contribution_score DECIMAL(5, 2) DEFAULT 0,
    late_minutes INTEGER DEFAULT 0,
    tasks_assigned INTEGER DEFAULT 0,
    tasks_completed INTEGER DEFAULT 0,
    tasks_failed INTEGER DEFAULT 0,
    incidents_logged INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(staff_id, date)
);

-- Indexing for lookups
CREATE INDEX IF NOT EXISTS idx_store_metrics_date ON agg_daily_store_metrics(date);
CREATE INDEX IF NOT EXISTS idx_store_metrics_code ON agg_daily_store_metrics(store_code);
CREATE INDEX IF NOT EXISTS idx_staff_metrics_date ON agg_daily_staff_metrics(date);
CREATE INDEX IF NOT EXISTS idx_staff_metrics_id ON agg_daily_staff_metrics(staff_id);
