-- Migration V3.22: Compliance Module - Food Safety & 5S
-- Purpose: Implementation of HACCP Temperature Logs and Hygiene Audits

-- 1. Bảng Log Nhiệt độ (HACCP Log)
-- Dùng để ghi nhận nhiệt độ tủ lạnh, tủ đông hằng ngày
CREATE TABLE IF NOT EXISTS op_temperature_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES system_tenants(id),
    store_code TEXT NOT NULL,
    staff_id TEXT NOT NULL,
    equipment_name TEXT NOT NULL, -- Tủ đông thịt, Tủ mát rau, v.v.
    temperature NUMERIC(5, 2) NOT NULL,
    unit TEXT DEFAULT 'C',
    is_safe BOOLEAN DEFAULT TRUE,
    action_taken TEXT, -- Nếu temperature cao quá thì đã làm gì
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bảng Checklist 5S & Vệ sinh hằng ngày
-- Dùng cho việc Audit vệ sinh sảnh/bếp
CREATE TABLE IF NOT EXISTS op_hygiene_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES system_tenants(id),
    store_code TEXT NOT NULL,
    staff_id TEXT NOT NULL,
    audit_type TEXT NOT NULL, -- MORNING_5S, NIGHT_CLEANING, DEEP_CLEAN
    score INTEGER, -- % hoàn thành checklist
    checklist_data JSONB NOT NULL, -- Chi tiết từng hạng mục
    photo_urls JSONB DEFAULT '[]', -- Ảnh minh chứng
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Cập nhật Permission cho Module Tuân thủ
INSERT INTO permissions_master (perm_key, domain, module, description)
VALUES 
('SUBMIT_TEMP_LOG', 'CORE', 'COMPLIANCE', 'Ghi nhật ký nhiệt độ thiết bị (ATTP)'),
('SUBMIT_HYGIENE_AUDIT', 'CORE', 'COMPLIANCE', 'Thực hiện báo cáo vệ sinh 5S'),
('VIEW_COMPLIANCE_REPORTS', 'CORE', 'COMPLIANCE', 'Xem báo cáo tuân thủ chi nhánh')
ON CONFLICT (perm_key) DO NOTHING;

-- Gán quyền mặc định cho STAFF, LEADER, SM
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES 
('STAFF', 'SUBMIT_TEMP_LOG', TRUE),
('STAFF', 'SUBMIT_HYGIENE_AUDIT', TRUE),
('LEADER', 'SUBMIT_TEMP_LOG', TRUE),
('LEADER', 'SUBMIT_HYGIENE_AUDIT', TRUE),
('LEADER', 'VIEW_COMPLIANCE_REPORTS', TRUE),
('SM', 'SUBMIT_TEMP_LOG', TRUE),
('SM', 'SUBMIT_HYGIENE_AUDIT', TRUE),
('SM', 'VIEW_COMPLIANCE_REPORTS', TRUE)
ON CONFLICT DO NOTHING;
