-- Migration V3.5: Store Mapping & New Master Data

-- 1. Add store_code mapping to existing master tables
-- Default 'ALL' means applies to all stores. Specific store code means specific override.
ALTER TABLE IF EXISTS checklist_master ADD COLUMN IF NOT EXISTS store_code VARCHAR(50) DEFAULT 'ALL';
ALTER TABLE IF EXISTS sub_position_master ADD COLUMN IF NOT EXISTS store_code VARCHAR(50) DEFAULT 'ALL';
ALTER TABLE IF EXISTS incident_master ADD COLUMN IF NOT EXISTS store_code VARCHAR(50) DEFAULT 'ALL';
ALTER TABLE IF EXISTS layout_master ADD COLUMN IF NOT EXISTS store_code VARCHAR(50) DEFAULT 'ALL';

-- 2. Create Role Master (Job Titles/Permissions)
CREATE TABLE IF NOT EXISTS role_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) UNIQUE NOT NULL, -- e.g. 'HEAD_CHEF'
    role_name VARCHAR(100) NOT NULL, -- 'Bếp Trưởng'
    description TEXT,
    store_code VARCHAR(50) DEFAULT 'ALL',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Shift Master (Shift Configurations)
CREATE TABLE IF NOT EXISTS shift_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code VARCHAR(50) UNIQUE NOT NULL, -- e.g. 'MORNING_6H'
    shift_name VARCHAR(100) NOT NULL, -- 'Ca Sáng (6h)'
    start_time TIME NOT NULL, -- '06:00'
    end_time TIME NOT NULL, -- '14:00'
    store_code VARCHAR(50) DEFAULT 'ALL',
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Initial Seed for Roles and Shifts
INSERT INTO role_master (role_code, role_name, description, store_code)
VALUES 
('HEAD_CHEF', 'Bếp Trưởng', 'Quản lý khu vực bếp', 'ALL'),
('CHEF', 'Đầu Bếp', 'Nhân viên bếp', 'ALL'),
('SERVER', 'Phục Vụ', 'Nhân viên bàn', 'ALL'),
('BARTENDER', 'Pha Chế', 'Nhân viên quầy bar', 'ALL'),
('RUNNER', 'Runner', 'Tiếp thực', 'ALL')
ON CONFLICT (role_code) DO NOTHING;

INSERT INTO shift_master (shift_code, shift_name, start_time, end_time, store_code)
VALUES
('MORNING', 'Ca Sáng', '06:00', '14:00', 'ALL'),
('AFTERNOON', 'Ca Chiều', '14:00', '22:00', 'ALL'),
('NIGHT', 'Ca Đêm', '22:00', '06:00', 'ALL'),
('FULL', 'Full Shift', '08:00', '20:00', 'ALL')
ON CONFLICT (shift_code) DO NOTHING;
