-- Migration V3.9: Decision Engine Core Backbone
-- Focus: Raw Event Logging & Signal Extraction

-- 1. Raw Operational events (Unified Fact Table)
-- This table stores a snapshot of every significant operational action
CREATE TABLE IF NOT EXISTS raw_operational_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL, -- 'SHIFT_LOG', 'LEADER_REPORT', 'INVENTORY', etc.
    source_id BIGINT, -- Original ID in the specific table
    store_code TEXT NOT NULL,
    staff_id BIGINT,
    role_code TEXT,
    event_time TIMESTAMPTZ DEFAULT NOW(),
    data JSONB NOT NULL, -- Full payload at the time of event
    hash TEXT UNIQUE, -- To prevent duplicate logging (e.g., md5 of significant fields)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Operational Signals (Flags)
-- These are the translated signals based on RULE_CATALOG_V3
CREATE TABLE IF NOT EXISTS operational_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT REFERENCES raw_operational_events(id),
    rule_code TEXT NOT NULL, -- e.g., 'R01', 'R12'
    flag_key TEXT NOT NULL, -- e.g., 'people_delay'
    severity TEXT CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    metadata JSONB, -- Context data: { late_minutes: 25, checklist_fail_count: 2 }
    is_valid BOOLEAN DEFAULT TRUE, -- Allows manager overrides
    override_reason TEXT,
    overridden_by BIGINT, -- link to staff_master(id)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Career Levels Config (Hard thresholds)
CREATE TABLE IF NOT EXISTS career_levels_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_code TEXT UNIQUE, -- 'L0', 'L1', 'L2', 'L3', 'L4'
    level_name TEXT,
    min_trust_score INTEGER NOT NULL,
    min_ops_score INTEGER NOT NULL,
    required_certifications JSONB DEFAULT '[]',
    min_days_in_level INTEGER DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Career Levels
INSERT INTO career_levels_config (level_code, level_name, min_trust_score, min_ops_score, min_days_in_level) VALUES
('L0', 'Newbie / Trainee', 0, 0, 0),
('L1', 'Reliable Crew', 80, 70, 30),
('L2', 'Skill Specialist', 85, 80, 60),
('L3', 'Future Leader', 90, 85, 90),
('L4', 'Elite Performer', 95, 90, 180)
ON CONFLICT (level_code) DO NOTHING;

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_raw_events_store ON raw_operational_events(store_code);
CREATE INDEX IF NOT EXISTS idx_signals_event ON operational_signals(event_id);
CREATE INDEX IF NOT EXISTS idx_raw_events_type ON raw_operational_events(event_type);
