-- Migration V3: Admin Console (Feature Flags & Permissions)

-- 1. System Feature Flags
CREATE TABLE IF NOT EXISTS system_feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flag_key TEXT UNIQUE NOT NULL,
    description TEXT,
    is_enabled BOOLEAN DEFAULT FALSE,
    enabled_env TEXT[] DEFAULT '{dev}', -- ['dev', 'prod']
    rollout_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Permissions Master (Catalog of all system permissions)
CREATE TABLE IF NOT EXISTS permissions_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_key TEXT UNIQUE NOT NULL, -- e.g., 'PAYROLL_EDIT'
    module TEXT NOT NULL, -- e.g., 'HR', 'OPERATION'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Role Permissions Matrix (Which role has which permission)
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code TEXT NOT NULL, -- Links to role_master logic (ADMIN, OPS, SM, LEADER, STAFF)
    perm_key TEXT NOT NULL REFERENCES permissions_master(perm_key) ON DELETE CASCADE,
    can_access BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(role_code, perm_key)
);

-- 4. Seed Initial Data (Updated for Real-world Specs)

-- Feature Flags (Modules)
INSERT INTO system_feature_flags (flag_key, description, is_enabled, enabled_env)
VALUES 
('MODULE_GAMIFICATION', 'Hệ thống Game (XP, Huy hiệu, Level)', FALSE, '{dev}'), -- Mặc định OFF theo yêu cầu
('MODULE_CAREER', 'Hồ sơ năng lực & KPI cá nhân', FALSE, '{dev}'), -- Mặc định OFF theo yêu cầu
('ADMIN_CONSOLE', 'Hệ thống quản trị tập trung', TRUE, '{dev,prod}')
ON CONFLICT (flag_key) DO UPDATE SET 
    description = EXCLUDED.description,
    is_enabled = EXCLUDED.is_enabled;

-- Permissions List
INSERT INTO permissions_master (perm_key, module, description)
VALUES 
-- Dashboard & Core
('VIEW_DASHBOARD', 'CORE', 'Xem bảng điều khiển cá nhân'),
('VIEW_ADMIN_CONSOLE', 'SYSTEM', 'Truy cập Admin Console'),

-- Operational Submission
('SUBMIT_SHIFTLOG', 'OPERATION', 'Gửi báo cáo ca làm việc (Staff)'),
('SUBMIT_LEADER_REPORT', 'OPERATION', 'Gửi báo cáo ca trưởng (Leader)'),
('SUBMIT_SM_REPORT', 'OPERATION', 'Gửi nhật ký quản lý (SM/OPS)'),

-- Approval & Management
('APPROVE_SHIFTLOG', 'MANAGEMENT', 'Duyệt báo cáo ca của nhân viên'),
('MANAGE_STAFF', 'HR', 'Quản lý nhân sự (Thêm/Sửa/Xóa)')

ON CONFLICT (perm_key) DO UPDATE SET description = EXCLUDED.description;

-- Role Matrix Defaults (Seed)
-- Reset logic: Insert/Update permission matrix based on role logic

-- ADMIN & OPS (Full Power)
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES
('ADMIN', 'VIEW_ADMIN_CONSOLE', TRUE),
('ADMIN', 'MANAGE_STAFF', TRUE),
('ADMIN', 'APPROVE_SHIFTLOG', TRUE),
('OPS', 'VIEW_ADMIN_CONSOLE', TRUE),
('OPS', 'SUBMIT_SM_REPORT', TRUE),
('OPS', 'APPROVE_SHIFTLOG', TRUE)
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = EXCLUDED.can_access;

-- SM (Store Manager)
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES
('SM', 'SUBMIT_SM_REPORT', TRUE),
('SM', 'SUBMIT_LEADER_REPORT', TRUE), -- SM can do Leader work
('SM', 'APPROVE_SHIFTLOG', TRUE),
('SM', 'MANAGE_STAFF', TRUE),
('SM', 'VIEW_ADMIN_CONSOLE', FALSE) -- SM cannot see Admin Console
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = EXCLUDED.can_access;

-- LEADER
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES
('LEADER', 'SUBMIT_LEADER_REPORT', TRUE),
('LEADER', 'SUBMIT_SHIFTLOG', TRUE), 
('LEADER', 'APPROVE_SHIFTLOG', FALSE) -- Leader generally doesn't final approve payroll
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = EXCLUDED.can_access;

-- STAFF
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES
('STAFF', 'SUBMIT_SHIFTLOG', TRUE),
('STAFF', 'SUBMIT_LEADER_REPORT', FALSE),
('STAFF', 'VIEW_ADMIN_CONSOLE', FALSE)
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = EXCLUDED.can_access;
