-- Migration V3: Admin Console (Feature Flags & Permissions)

-- 1. System Feature Flags
CREATE TABLE IF NOT EXISTS system_feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flag_key TEXT UNIQUE NOT NULL,
    description TEXT,
    is_enabled BOOLEAN DEFAULT FALSE,
    enabled_env TEXT[] DEFAULT '{dev}', -- ['dev', 'prod']
    rollout_percentage INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Permissions Master (Catalog of all system permissions)
CREATE TABLE IF NOT EXISTS permissions_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_key TEXT UNIQUE NOT NULL, -- e.g., 'PAYROLL_EDIT'
    module TEXT NOT NULL, -- e.g., 'HR', 'OPERATION'
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Role Permissions Matrix (Which role has which permission)
CREATE TABLE IF NOT EXISTS role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code TEXT NOT NULL, -- Links to role_master logic (ADMIN, OPS, SM, LEADER, STAFF)
    perm_key TEXT NOT NULL REFERENCES permissions_master(perm_key) ON DELETE CASCADE,
    can_access BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(role_code, perm_key)
);

-- 4. Seed Initial Data (Example)
-- Features
INSERT INTO system_feature_flags (flag_key, description, is_enabled, enabled_env)
VALUES 
('OPS_INTELLIGENCE', 'Advanced AI Analytics', FALSE, '{dev}'),
('ADMIN_CONSOLE', 'New Admin System', TRUE, '{dev,prod}')
ON CONFLICT (flag_key) DO NOTHING;

-- Permissions
INSERT INTO permissions_master (perm_key, module, description)
VALUES 
('VIEW_DASHBOARD', 'CORE', 'View personal dashboard'),
('SUBMIT_SHIFTLOG', 'OPERATION', 'Submit daily shift log'),
('APPROVE_SHIFTLOG', 'OPERATION', 'Approve staff shift logs'),
('MANAGE_FLAGS', 'SYSTEM', 'Manage Feature Flags')
ON CONFLICT (perm_key) DO NOTHING;

-- Role Matrix (Example defaults)
INSERT INTO role_permissions (role_code, perm_key, can_access)
VALUES
('ADMIN', 'MANAGE_FLAGS', TRUE),
('STAFF', 'SUBMIT_SHIFTLOG', TRUE),
('LEADER', 'SUBMIT_SHIFTLOG', TRUE)
ON CONFLICT (role_code, perm_key) DO NOTHING;
