-- TM OPERATION APP V3 - BOOTSTRAP SQL
-- Run this in Supabase Studio (SQL Editor) to enable Decision Engine features.

-- 1. Upgrade staff_master with career tracking
ALTER TABLE staff_master 
ADD COLUMN IF NOT EXISTS current_level TEXT DEFAULT 'L0',
ADD COLUMN IF NOT EXISTS trust_score DECIMAL(10, 2) DEFAULT 100,
ADD COLUMN IF NOT EXISTS performance_score DECIMAL(10, 2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS promotion_eligible BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS last_score_update TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS level_changed_at TIMESTAMPTZ DEFAULT NOW();

-- 2. Create index for career tracking
CREATE INDEX IF NOT EXISTS idx_staff_career ON staff_master(current_level, promotion_eligible);

-- 3. Ensure career levels config exists
CREATE TABLE IF NOT EXISTS career_levels_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_code TEXT UNIQUE NOT NULL,
    level_name TEXT,
    min_trust_score INTEGER NOT NULL,
    min_ops_score INTEGER NOT NULL,
    required_certifications JSONB DEFAULT '[]',
    min_days_in_level INTEGER DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Career Levels
INSERT INTO career_levels_config (level_code, level_name, min_trust_score, min_ops_score, min_days_in_level) VALUES
('L0', 'Newbie / Trainee', 0, 0, 0),
('L1', 'Reliable Crew', 80, 70, 30),
('L2', 'Skill Specialist', 85, 80, 60),
('L3', 'Future Leader', 90, 85, 90),
('L4', 'Elite Performer', 95, 90, 180)
ON CONFLICT (level_code) DO NOTHING;

-- 4. Re-verify/Fix Feature Flags Domains
ALTER TABLE system_feature_flags ADD COLUMN IF NOT EXISTS domain TEXT DEFAULT 'CORE';

UPDATE system_feature_flags SET domain = 'ADMIN' WHERE flag_key IN ('ADMIN_CONSOLE', 'MODULE_DIVINE_MODE');
UPDATE system_feature_flags SET domain = 'INTELLIGENCE' WHERE flag_key IN ('MODULE_DECISION_ENGINE', 'MODULE_QAQC_HUB');
UPDATE system_feature_flags SET domain = 'FINANCIAL' WHERE flag_key IN ('MODULE_REVENUE_METRICS');
UPDATE system_feature_flags SET domain = 'TALENT' WHERE flag_key IN ('MODULE_GAMIFICATION', 'MODULE_CAREER');
UPDATE system_feature_flags SET domain = 'LAB' WHERE flag_key LIKE 'LAB_%';

-- 5. Add Missing Lab Flags
INSERT INTO system_feature_flags (flag_key, description, is_enabled, domain, enabled_env)
VALUES 
('LAB_DECISION_SIMULATOR', '🧬 [LAB] Mô phỏng kết quả của 60+ Rules trên dữ liệu thật', FALSE, 'LAB', '{dev}'),
('LAB_RISK_RADAR', '🧬 [LAB] Radar nhận diện rủi ro vận hành bằng AI', FALSE, 'LAB', '{dev}'),
('LAB_PREDICTIVE_LABOR', '🧬 [LAB] Dự báo số lượng nhân sự cần thiết dựa trên Traffic', FALSE, 'LAB', '{dev}')
ON CONFLICT (flag_key) DO UPDATE SET domain = 'LAB';
