-- ==========================================================
-- BẢN MASTER SYNC V5.1: RE-FOCUS CORE OPERATION & LAB V3
-- Mục tiêu: Chuyển các tính năng tính toán V3 sang LAB
-- Tập trung hoàn thiện Core Operation (Vận hành cốt lõi)
-- ==========================================================

-- 1. CẬP NHẬT DOMAIN CHO FEATURE FLAGS (Chuyển sang LAB)
UPDATE system_feature_flags SET domain = 'LAB' WHERE flag_key IN ('MODULE_DECISION_ENGINE', 'MODULE_OPERATION_METRICS', 'MODULE_DECISION_CONSOLE', 'LAB_DECISION_SIMULATOR');
UPDATE system_feature_flags SET domain = 'ADMIN' WHERE flag_key IN ('ADMIN_CONSOLE', 'MODULE_DIVINE_MODE');
UPDATE system_feature_flags SET domain = 'CORE' WHERE flag_key IN ('MODULE_SHIFTLOG', 'MODULE_SM_REPORT', 'MODULE_INVENTORY', 'MODULE_CASHIER');

-- 2. ĐỊNH NGHĨA LẠI MA TRẬN PERMISSIONS (Gắn Domain chuẩn)
DELETE FROM permissions_master;

INSERT INTO permissions_master (perm_key, domain, module, description)
VALUES 
-- [ADMIN] QUẢN TRỊ & BẢO MẬT
('VIEW_ADMIN_CONSOLE', 'ADMIN', 'SYSTEM', 'Truy cập Trung tâm Quản trị'),
('MANAGE_STAFF', 'ADMIN', 'HR', 'Quản trị nhân sự (Admin level)'),
('VIEW_AUDIT_LOGS', 'ADMIN', 'AUDIT', 'Xem nhật ký hoạt động hệ thống'),
('MANAGE_SYSTEM_CONFIG', 'ADMIN', 'SYSTEM', 'Thay đổi cấu hình cờ tính năng & phân quyền'),

-- [LAB] CÁC TÍNH NĂNG V3 ĐANG PHÁT TRIỂN
('VIEW_DECISION_CONSOLE', 'LAB', 'DECISION', 'Xem bảng thăng tiến & Career Path (V3 Beta)'),
('EXECUTE_PROMOTION', 'LAB', 'DECISION', 'Thực hiện lệnh thăng cấp nhân sự (V3 Beta)'),
('VIEW_OPS_METRICS', 'LAB', 'ANALYTICS', 'Xem radar chỉ số vận hành BOD (V3 Beta)'),

-- [CORE] VẬN HÀNH CỐT LÕI (MỤC TIÊU HOÀN THIỆN)
('SUBMIT_SHIFTLOG', 'CORE', 'OPERATION', 'Gửi báo cáo ca làm việc (Staff)'),
('SUBMIT_LEADER_REPORT', 'CORE', 'OPERATION', 'Gửi báo cáo ca trưởng (Leader)'),
('MANAGE_FACILITIES', 'CORE', 'FACILITY', 'Báo cáo & Theo dõi sửa chữa thiết bị'), -- [NEW CORE]
('SUBMIT_INVENTORY', 'CORE', 'STOCK', 'Báo cáo kiểm kho & Hàng hủy hằng ngày'), -- [NEW CORE]
('SUBMIT_CASHIER_REPORT', 'CORE', 'FINANCE', 'Chốt ca thu ngân & Đối soát tiền mặt'), -- [NEW CORE]
('VIEW_STORE_DASHBOARD', 'CORE', 'VIEW', 'Xem Dashboard vận hành cửa hàng');

-- 3. CẤU TRÚC BẢNG CHO CORE OPERATION THIẾU SÓT
-- Bảng quản lý Sự cố Thiết bị (Facilities)
CREATE TABLE IF NOT EXISTS op_facility_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code TEXT NOT NULL,
    staff_id TEXT NOT NULL,
    item_name TEXT NOT NULL,
    issue_description TEXT,
    priority TEXT DEFAULT 'NORMAL', -- LOW, NORMAL, HIGH, URGENT
    status TEXT DEFAULT 'OPEN', -- OPEN, IN_PROGRESS, RESOLVED, CANCELLED
    photo_url TEXT,
    fixed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bảng Chốt ca Thu ngân (Cashier Closing)
CREATE TABLE IF NOT EXISTS op_cashier_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code TEXT NOT NULL,
    staff_id TEXT NOT NULL,
    report_date DATE DEFAULT CURRENT_DATE,
    shift_code TEXT,
    system_revenue NUMERIC(15, 2) DEFAULT 0,
    actual_cash NUMERIC(15, 2) DEFAULT 0,
    mismatch_reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ĐỒNG BỘ QUYỀN CHO IT & ADMIN (Auto-grant all)
INSERT INTO role_permissions (role_code, perm_key, can_access)
SELECT 'IT', perm_key, TRUE FROM permissions_master
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = TRUE;

INSERT INTO role_permissions (role_code, perm_key, can_access)
SELECT 'ADMIN', perm_key, TRUE FROM permissions_master
ON CONFLICT (role_code, perm_key) DO UPDATE SET can_access = TRUE;
